var currentRouteName, func, helpers, isSubReady, name, param, pathFor, queryParam, subsReady, urlFor,
  slice = [].slice,
  hasProp = {}.hasOwnProperty;

subsReady = function() {
  var subs;
  subs = 1 <= arguments.length ? slice.call(arguments, 0) : [];
  if (subs.length === 1) {
    return FlowRouter.subsReady();
  }
  subs = subs.slice(0, subs.length - 1);
  return _.reduce(subs, function(memo, sub) {
    return memo && FlowRouter.subsReady(sub);
  }, true);
};

pathFor = function(path, view) {
  var query, ref;
  if (!path) {
    throw new Error('no path defined');
  }
  if (((ref = path.hash) != null ? ref.route : void 0) != null) {
    view = path;
    path = view.hash.route;
    delete view.hash.route;
  }
  query = view.hash.query ? FlowRouter._qs.parse(view.hash.query) : {};
  return FlowRouter.path(path, view.hash, query);
};

urlFor = function(path, view) {
  var relativePath;
  relativePath = pathFor(path, view);
  return Meteor.absoluteUrl(relativePath.substr(1));
};

param = function(name) {
  return FlowRouter.getParam(name);
};

queryParam = function(key) {
  return FlowRouter.getQueryParam(key);
};

currentRouteName = function() {
  return FlowRouter.getRouteName();
};

isSubReady = function(sub) {
  if (sub) {
    return FlowRouter.subsReady(sub);
  }
  return FlowRouter.subsReady();
};

helpers = {
  subsReady: subsReady,
  pathFor: pathFor,
  urlFor: urlFor,
  param: param,
  queryParam: queryParam,
  currentRouteName: currentRouteName,
  isSubReady: isSubReady
};

for (name in helpers) {
  if (!hasProp.call(helpers, name)) continue;
  func = helpers[name];
  Template.registerHelper(name, func);
}

// ---
// generated by coffee-script 1.9.2
